<a href="https://colab.research.google.com/github/bunyanutn-droid/PythonDataViz/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import pandas
`pandas` เป็นไลบรารี (Library) ของภาษา Python ที่ใช้สำหรับ จัดการ วิเคราะห์ และประมวลผลข้อมูล โดยเฉพาะข้อมูลในรูปแบบ ตาราง (Table) เช่น ไฟล์ Excel, CSV, หรือฐานข้อมูล

In [1]:
import pandas as pd

###เชื่อม colab กับ drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
import os

path = '/content/drive/My Drive/Data_VIZ2026'

สร้างที่อยู่ไฟล์ (File Path) ของไฟล์ Data_Covid.csv โดยใช้ไลบรารี os
`os` เป็นไลบรารี่มาตรฐานของ python ที่ใช้จัดการระบบปฎิบัติการ เช่น โฟลเดอร์ ไฟล์ และพาธ
`path` คือตัวแปรที่เก็บตำแหน่งของโฟลเดอร์

In [12]:
covid_file_path = os.path.join(path,'Data_Covid.csv')
print(covid_file_path)

/content/drive/My Drive/Data_VIZ2026/Data_Covid.csv

In [13]:
a = path + '/Data_Covid.csv'
print(a)

/content/drive/My Drive/Data_VIZ2026/Data_Covid.csv

###clean data

In [80]:
data_covid.isnull().sum()

No.                          0
announce_date                0
Notified date                0
sex                      17655
age                      31217
Unit                     31217
nationality              32046
province_of_isolation        0
risk                         0
province_of_onset        34842
district_of_onset        43974
dtype: int64

## load data to memory
สั่งให้อ่านไฟล์ csv
โค้ดที่ใช้อ่านไฟล์ excel คือ` pd.read_excel `
ถ้ามีหลายชีทสามารถระบุชีทได้ `df = pd.read_excel("Data.xlsx", sheet_name=0)`

In [15]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_613/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
data_covid.head() #แสดงข้อมูล5แถวแรก

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

In [17]:
data_covid.tail() #แสดงข้อมูล5แถวสุดท้าย

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [20]:
data_covid.shape #ดูขนาดของตารางข้อมูล โดยจะแสดง(จำนวนแถว, จำนวนคอลัมน์)

(356612, 11)

## ชี้ค่าในตาราง

#### basic

In [21]:
data_covid['province_of_onset'] #เป็นการเรียกโดยระบุชื่อคอลัมน์

0         เชียงใหม่
1         เชียงใหม่
2         เชียงใหม่
3               NaN
4         เชียงใหม่
            ...
356607          NaN
356608          NaN
356609          NaN
356610          NaN
356611          NaN
Name: province_of_onset, Length: 356612, dtype: object

In [23]:
data_covid['province_of_onset'][4] #เลือกคอลัมน์ province_of_onset เลือกข้อมูลที่ Index = 4
#ผลลัพธ์ที่ได้คือ ค่าเพียง 1 ค่า (เช่น ชื่อจังหวัดของแถวที่มี Index เท่ากับ 4)

'เชียงใหม่'

In [24]:
data_covid['province_of_onset'].count() #นับจำนวนข้อมูล

np.int64(321770)

In [25]:
data_covid['province_of_onset'].unique() #ดูค่าที่ไม่ซ้ำ

array(['เชียงใหม่', nan, 'เชียงราย', 'อุตรดิตถ์', 'น่าน', 'ลำปาง', 'แพร่',
       'แม่ฮ่องสอน', 'พะเยา', 'ลำพูน', 'พิษณุโลก', 'นครสวรรค์', 'พิจิตร',
       'กำแพงเพชร', 'สุโขทัย', 'เลย', 'นนทบุรี', 'เพชรบูรณ์', 'ตาก',
       'ชัยนาท', 'อุทัยธานี', 'กรุงเทพมหานคร', 'นครปฐม', 'ปทุมธานี',
       'สมุทรปราการ', 'พระนครศรีอยุธยา', 'กาญจนบุรี', 'ฉะเชิงเทรา',
       'สุพรรณบุรี', 'นครนายก', 'อุบลราชธานี', 'บุรีรัมย์', 'นครพนม',
       'หนองคาย', 'อุดรธานี', 'นครศรีธรรมราช', 'อ่างทอง', 'สระบุรี',
       'สมุทรสงคราม', 'สุรินทร์', 'นครราชสีมา', 'ลพบุรี', 'ชัยภูมิ',
       'กาฬสินธุ์', 'อำนาจเจริญ', 'ยโสธร', 'ขอนแก่น', 'สิงห์บุรี',
       'เพชรบุรี', 'สมุทรสาคร', 'ราชบุรี', 'ชลบุรี', 'สกลนคร', 'นนทบุุรี',
       'ประจวบคีรีขันธ์', 'อยุธยา', 'จันทบุรี', 'ระยอง', 'สระแก้ว',
       'ปราจีนบุรี', 'มหาสารคาม', 'หนองบัวลำภู', 'บุรีรัมย์์', 'ตราด',
       'ร้อยเอ็ด', 'บึงกาฬ', 'ศรีสะเกษ', 'มุกดาหาร', 'ตรัง',
       'สุราษฎร์ธานี', 'ระนอง', 'ภูเก็ต', 'กระบี่', 'พังงา', 'ชุมพร',
       'พัทลุง', 'นราธิวาส', 'ปัตตานี', 'ยะลา', 'สงขลา', 'สตูล',
       'Cambodia', 'หัวไทร', 'กัมพูชา', 'เมืองนครศรีธรรมราช', 'แพร่่',
       'ปทุุมธานี', 'สงขลา\u200b', 'สุุโขทัย', 'ฃัยภูมิ', 'กาฬสินธ์',
       'ส\u200bงขลา', 'สุมทรสาคร', 'นครศรีธรรมราช\u200b', 'ชอนแก่น',
       'สุทรสาคร', 'จันทรบุรี', 'นคราชสีมา'], dtype=object)

In [26]:
data_covid['province_of_onset'].value_counts() #นับจำนวนข้อมูลแต่ละจังหวัด

province_of_onset
กรุงเทพมหานคร     57632
ชลบุรี            12941
ขอนแก่น           12821
สมุทรปราการ       11826
นนทบุรี           10641
                  ...
ส​งขลา                1
นครศรีธรรมราช​        1
ชอนแก่น               1
สุทรสาคร              1
จันทรบุรี             1
Name: count, Length: 97, dtype: int64

#### .iloc ย่อมาจาก Integer Location
ใช้เลือกข้อมูลตามตำแหน่ง [แถว,คอลัมน์] การนับจะเริ่มจาก 0 1 2 ...
#ข้อดีของ iloc
* เหมาะเมื่อรู้ตำแหน่งของข้อมูล
* แต่ไม่ทราบชื่อคอลัมน์
ใช้งานสะดวกในการเลือกช่วงข้อมูล

In [27]:
data_covid.iloc[4,7]

'เชียงใหม่'

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [28]:
smaller_table = data_covid[['announce_date','province_of_onset','risk']] #เรียกคอลัมน์ที่ต้องการมาเรียงต่อกันคล้ายๆ ลิสต์ อย่าลืมใส่ '' ครอบชื่อคอลัมน์
smaller_table

       announce_date province_of_onset                  risk
0          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
1          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
2          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
3          12/4/2022               NaN  อยู่ระหว่างการสอบสวน
4          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
...              ...               ...                   ...
356607      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356608      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356609      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356610      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356611      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ

[356612 rows x 3 columns]

#### ตัดเฉพาะ rows ที่ต้องการ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [ ]:
data_covid.iloc[1:5,:]

   No. announce_date  ... district_of_onset                              risk
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 10 columns]

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)

In [ ]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

         No.  ...                                           risk
180      181  ...                                        สนามมวย
462      463  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466    1467  ...                  คนไทยเดินทางกลับจากต่างประเทศ
1970    1971  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637    2638  ...                  สัมผัสผู้เดินทางจากต่างประเทศ
2673    2674  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
5948    5949  ...                              Cluster สมุทรสาคร
6082    6083  ...                              Cluster สมุทรสาคร
9333    9334  ...                           อยู่ระหว่างการสอบสวน
9334    9335  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10610  10611  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11517  11518  ...                           อยู่ระหว่างการสอบสวน
11697  11698  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11698  11699  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[14 rows x 10 columns]

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [ ]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6    7     1/26/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
7    8     1/26/2020  ...            หัวหิน  คนต่างชาติเดินทางมาจากต่างประเทศ

[8 rows x 10 columns]

In [ ]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[4 rows x 10 columns]

In [ ]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [ ]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
6    7     1/26/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[6 rows x 10 columns]

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

### HW6

In [29]:
data = data_covid[['sex','age','province_of_onset']]

In [30]:
data

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0               NaN
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356607   ชาย   NaN               NaN
356608   ชาย   NaN               NaN
356609  หญิง   NaN               NaN
356610  หญิง   NaN               NaN
356611   ชาย   NaN               NaN

[356612 rows x 3 columns]

In [95]:
data = data_covid.fillna(value={'sex':'ไม่รู้', 'province_of_onset':'ไม่รู้'})
data

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,ไม่รู้,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN

In [102]:
data_clean= data.dropna(subset=['age']) #data มี missing ต้องทำการclean data

In [103]:
data_clean

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,ไม่รู้,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356591,4262464,1/5/2022,30/4/2022,ชาย,7.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง
356592,4262465,1/5/2022,30/4/2022,หญิง,27.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,หลักสี่
356593,4262466,1/5/2022,30/4/2022,ชาย,69.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,มีนบุรี
356594,4262467,1/5/2022,30/4/2022,ชาย,19.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,NaN
356595,4262468,1/5/2022,30/4/2022,หญิง,35.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,NaN

In [104]:
this_data_clean= data_clean[['sex','age','province_of_onset']]

In [105]:
this_data_clean

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0            ไม่รู้
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356591   ชาย   7.0     กรุงเทพมหานคร
356592  หญิง  27.0     กรุงเทพมหานคร
356593   ชาย  69.0     กรุงเทพมหานคร
356594   ชาย  19.0     กรุงเทพมหานคร
356595  หญิง  35.0     กรุงเทพมหานคร

[325395 rows x 3 columns]

In [106]:
Female = this_data_clean[this_data_clean['sex']=='หญิง']
Female['age']

0         54.0
1         36.0
2         31.0
4         33.0
5         12.0
          ...
356586    44.0
356587    49.0
356589     1.0
356592    27.0
356595    35.0
Name: age, Length: 186838, dtype: object

In [107]:
Male = this_data_clean[this_data_clean['sex']=='ชาย']
Male['age']

3         37.0
6         32.0
9         42.0
11        41.0
13        37.0
          ...
356588     6.0
356590    36.0
356591     7.0
356593    69.0
356594    19.0
Name: age, Length: 125159, dtype: object

In [112]:
print(Female['age'].dtype)

object

In [113]:
print(Female['age'].head(20))

0     54.0
1     36.0
2     31.0
4     33.0
5     12.0
7     55.0
8     45.0
10    37.0
12    28.0
15    39.0
16    34.0
17    88.0
18     9.0
22    39.0
24    41.0
25    24.0
26    26.0
29    55.0
30    68.0
32    26.0
Name: age, dtype: object

In [126]:
total_age_sum = 0
N = 0

for a in Female['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)            # แปลงเป็น int
        if a > 0:
            total_age_sum += a
            N += 1

print( f'อายุเฉลี่ยของผู้หญิง {total_age_sum/N}')
#-----------------------------------------------------------------------------------
total_age_Male = 0
N = 0

for a in Male['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)            # แปลงเป็น int
        if a > 0:
            total_age_Male += a
            N += 1

print( f'อายุเฉลี่ยของผู้ชาย {total_age_Male/N}')
#-----------------------------------------------------------------
Female_KK = Female[Female['province_of_onset']=='ขอนแก่น']

sum_female_kk = 0
N_female_kk = 0
for a in Female_KK['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)
        if a > 0:
            sum_female_kk += a # sum = sum + a
            N_female_kk += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum_female_kk/N_female_kk}')

male_KK =Male[Male['province_of_onset']=='ขอนแก่น']

sum_male_kk = 0
N_male_kk = 0
for a in male_KK['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)
        if a > 0:
            sum_male_kk += a # sum = sum + a
            N_male_kk += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น {sum_male_kk/N_male_kk}')

อายุเฉลี่ยของผู้หญิง 41.51104253203066
อายุเฉลี่ยของผู้ชาย 39.34756559167694
อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 39.65815760266371
อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น 37.1078811369509

In [71]:
this_data = data_covid[['sex','age','province_of_onset']]

In [42]:
this_data

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0               NaN
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356607   ชาย   NaN               NaN
356608   ชาย   NaN               NaN
356609  หญิง   NaN               NaN
356610  หญิง   NaN               NaN
356611   ชาย   NaN               NaN

[356612 rows x 3 columns]

In [120]:
female = this_data[this_data['sex']=='หญิง']
female['age']

0         54.0
1         36.0
2         31.0
4         33.0
5         12.0
          ...
356592    27.0
356595    35.0
356597     NaN
356609     NaN
356610     NaN
Name: age, Length: 203340, dtype: object

In [121]:
sum = 0
N = 0
for a in female['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum/N}')

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in female_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 41.57142857142857

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [ ]:
this_data.shape #(12423, 3)

(12653, 3)

In [ ]:
print(data_covid.shape)
print(data_covid.dropna().shape)

(12653, 10)
(6655, 10)

In [ ]:
this_data.dropna().shape

(8478, 3)

In [ ]:
this_data.dropna()

        sex   age province_of_onset
0      หญิง  61.0     กรุงเทพมหานคร
1      หญิง  74.0     กรุงเทพมหานคร
2      หญิง  73.0            นครปฐม
3       ชาย  68.0     กรุงเทพมหานคร
4      หญิง  66.0     กรุงเทพมหานคร
...     ...   ...               ...
12648  หญิง  44.0            ชลบุรี
12649  หญิง  52.0             ระยอง
12650  หญิง  23.0             ระยอง
12651  หญิง  29.0             ระยอง
12652  หญิง  22.0               ตาก

[8478 rows x 3 columns]

In [ ]:
this_data.dropna()
print(this_data.shape)

(12653, 3)

In [ ]:
this_data.dropna(inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
this_data.dropna(inplace=True)
print(this_data.shape)

(8478, 3)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(12653, 3)

In [ ]:
this_data.dropna().shape

(8478, 3)

In [ ]:
this_data.dropna(subset=['age']).shape

(8881, 3)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 12653
จำนวน record หลัง drop missing ใน province 10662

In [ ]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
this_data_updated[this_data_updated['sex']=='ไม่รู้']

          sex  age province_of_onset
4391   ไม่รู้ -1.0         สมุทรสาคร
4392   ไม่รู้ -1.0         สมุทรสาคร
4393   ไม่รู้ -1.0         สมุทรสาคร
4394   ไม่รู้ -1.0         สมุทรสาคร
4395   ไม่รู้ -1.0         สมุทรสาคร
...       ...  ...               ...
12635  ไม่รู้ -1.0         สมุทรสาคร
12636  ไม่รู้ -1.0         สมุทรสาคร
12637  ไม่รู้ -1.0         สมุทรสาคร
12638  ไม่รู้ -1.0         สมุทรสาคร
12639  ไม่รู้ -1.0         สมุทรสาคร

[2502 rows x 3 columns]

In [ ]:
this_data_updated['province_of_onset']=='ไม่รู้'

0        False
1        False
2        False
3        False
4        False
         ...
12648    False
12649    False
12650    False
12651    False
12652    False
Name: province_of_onset, Length: 12653, dtype: bool

In [ ]:
data_covid[this_data_updated['province_of_onset']=='ไม่รู้']

         No.  ...                                         risk
414      415  ...                                      สนามมวย
529      530  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
555      556  ...                                      สนามมวย
576      577  ...                                      สนามมวย
588      589  ...                         อยู่ระหว่างการสอบสวน
...      ...  ...                                          ...
12405  12406  ...                            Cluster สมุทรสาคร
12406  12407  ...                            Cluster สมุทรสาคร
12407  12408  ...                            Cluster สมุทรสาคร
12408  12409  ...                            Cluster สมุทรสาคร
12409  12410  ...                            Cluster สมุทรสาคร

[1991 rows x 10 columns]

In [ ]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})

In [ ]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

       sex  age province_of_onset
4391   NaN  NaN         สมุทรสาคร
4392   NaN  NaN         สมุทรสาคร
4393   NaN  NaN         สมุทรสาคร
4394   NaN  NaN         สมุทรสาคร
4395   NaN  NaN         สมุทรสาคร
...    ...  ...               ...
12635  NaN  NaN         สมุทรสาคร
12636  NaN  NaN         สมุทรสาคร
12637  NaN  NaN         สมุทรสาคร
12638  NaN  NaN         สมุทรสาคร
12639  NaN  NaN         สมุทรสาคร

[2502 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

(9334, sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [ ]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

9334
sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

       No.  ...                                               risk
6884  6885  ...                                  Cluster สมุทรสาคร
6885  6886  ...                                      Cluster ระยอง
6886  6887  ...                                        สถานบันเทิง
6887  6888  ...                                  Cluster สมุทรสาคร
6888  6889  ...  อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...

[5 rows x 10 columns]

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.          age
count  12653.000000  8881.000000
mean    6327.000000    38.054748
std     3652.750813    15.125178
min        1.000000     0.100000
25%     3164.000000    27.000000
50%     6327.000000    36.000000
75%     9490.000000    48.000000
max    12653.000000    97.000000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

39.46076940331987

### ```.isnull()```

In [ ]:
data_covid.isnull()

         No.  announce_date  ...  district_of_onset   risk
0      False          False  ...               True  False
1      False          False  ...               True  False
2      False          False  ...              False  False
3      False          False  ...               True  False
4      False          False  ...               True  False
...      ...            ...  ...                ...    ...
12648  False          False  ...              False  False
12649  False          False  ...              False  False
12650  False          False  ...              False  False
12651  False          False  ...              False  False
12652  False          False  ...              False  False

[12653 rows x 10 columns]

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table