<a href="https://colab.research.google.com/github/bunyanutn-droid/PythonDataViz/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import pandas
`pandas` เป็นไลบรารี (Library) ของภาษา Python ที่ใช้สำหรับ จัดการ วิเคราะห์ และประมวลผลข้อมูล โดยเฉพาะข้อมูลในรูปแบบ ตาราง (Table) เช่น ไฟล์ Excel, CSV, หรือฐานข้อมูล

In [ ]:
import pandas as pd

###เชื่อม colab กับ drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

path = '/content/drive/My Drive/Data_VIZ2026' #บนวินโดว์ใช้//

สร้างที่อยู่ไฟล์ (File Path) ของไฟล์ Data_Covid.csv โดยใช้ไลบรารี os
`os` เป็นไลบรารี่มาตรฐานของ python ที่ใช้จัดการระบบปฎิบัติการ เช่น โฟลเดอร์ ไฟล์ และพาธ
`path` คือตัวแปรที่เก็บตำแหน่งของโฟลเดอร์

In [ ]:
covid_file_path = os.path.join(path,'Data_Covid.csv')
print(covid_file_path)

/content/drive/My Drive/Data_VIZ2026/Data_Covid.csv

In [ ]:
a = path + '/Data_Covid.csv'
print(a)

/content/drive/My Drive/Data_VIZ2026/Data_Covid.csv

###clean data

In [ ]:
data_covid.isnull().sum()

No.                          0
announce_date                0
Notified date                0
sex                      17655
age                      31217
Unit                     31217
nationality              32046
province_of_isolation        0
risk                         0
province_of_onset        34842
district_of_onset        43974
dtype: int64

## load data to memory
สั่งให้อ่านไฟล์ csv
โค้ดที่ใช้อ่านไฟล์ excel คือ` pd.read_excel `
ถ้ามีหลายชีทสามารถระบุชีทได้ `df = pd.read_excel("Data.xlsx", sheet_name=0)`
ถ้าตอนใช้ import pandas ตอนอ่านก็ใช้ pandas.read

In [ ]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_23092/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
data_covid.head() #แสดงข้อมูล5แถวแรก สามารถใส่ตัวเลขใน()ได้ว่าจะเอากี่ข้อมูล

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

In [ ]:
data_covid.tail() #แสดงข้อมูล5แถวสุดท้าย

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
data_covid.shape #ดูขนาดของตารางข้อมูล โดยจะแสดง(จำนวนแถว, จำนวนคอลัมน์)

(356612, 11)

## ชี้ค่าในตาราง

#### basic

In [ ]:
data_covid['province_of_onset'] #เป็นการเรียกโดยระบุชื่อคอลัมน์

0         เชียงใหม่
1         เชียงใหม่
2         เชียงใหม่
3               NaN
4         เชียงใหม่
            ...
356607          NaN
356608          NaN
356609          NaN
356610          NaN
356611          NaN
Name: province_of_onset, Length: 356612, dtype: object

In [ ]:
data_covid['province_of_onset'][4] #เลือกคอลัมน์ province_of_onset เลือกข้อมูลที่ Index = 4
#ผลลัพธ์ที่ได้คือ ค่าเพียง 1 ค่า (เช่น ชื่อจังหวัดของแถวที่มี Index เท่ากับ 4)

'เชียงใหม่'

In [ ]:
data_covid['province_of_onset'].count() #นับจำนวนข้อมูล

np.int64(321770)

In [ ]:
data_covid['province_of_onset'].unique() #ดูค่าที่ไม่ซ้ำ

array(['เชียงใหม่', nan, 'เชียงราย', 'อุตรดิตถ์', 'น่าน', 'ลำปาง', 'แพร่',
       'แม่ฮ่องสอน', 'พะเยา', 'ลำพูน', 'พิษณุโลก', 'นครสวรรค์', 'พิจิตร',
       'กำแพงเพชร', 'สุโขทัย', 'เลย', 'นนทบุรี', 'เพชรบูรณ์', 'ตาก',
       'ชัยนาท', 'อุทัยธานี', 'กรุงเทพมหานคร', 'นครปฐม', 'ปทุมธานี',
       'สมุทรปราการ', 'พระนครศรีอยุธยา', 'กาญจนบุรี', 'ฉะเชิงเทรา',
       'สุพรรณบุรี', 'นครนายก', 'อุบลราชธานี', 'บุรีรัมย์', 'นครพนม',
       'หนองคาย', 'อุดรธานี', 'นครศรีธรรมราช', 'อ่างทอง', 'สระบุรี',
       'สมุทรสงคราม', 'สุรินทร์', 'นครราชสีมา', 'ลพบุรี', 'ชัยภูมิ',
       'กาฬสินธุ์', 'อำนาจเจริญ', 'ยโสธร', 'ขอนแก่น', 'สิงห์บุรี',
       'เพชรบุรี', 'สมุทรสาคร', 'ราชบุรี', 'ชลบุรี', 'สกลนคร', 'นนทบุุรี',
       'ประจวบคีรีขันธ์', 'อยุธยา', 'จันทบุรี', 'ระยอง', 'สระแก้ว',
       'ปราจีนบุรี', 'มหาสารคาม', 'หนองบัวลำภู', 'บุรีรัมย์์', 'ตราด',
       'ร้อยเอ็ด', 'บึงกาฬ', 'ศรีสะเกษ', 'มุกดาหาร', 'ตรัง',
       'สุราษฎร์ธานี', 'ระนอง', 'ภูเก็ต', 'กระบี่', 'พังงา', 'ชุมพร',
       'พัทลุง', 'นราธิวาส', 'ปัตตานี', 'ยะลา', 'สงขลา', 'สตูล',
       'Cambodia', 'หัวไทร', 'กัมพูชา', 'เมืองนครศรีธรรมราช', 'แพร่่',
       'ปทุุมธานี', 'สงขลา\u200b', 'สุุโขทัย', 'ฃัยภูมิ', 'กาฬสินธ์',
       'ส\u200bงขลา', 'สุมทรสาคร', 'นครศรีธรรมราช\u200b', 'ชอนแก่น',
       'สุทรสาคร', 'จันทรบุรี', 'นคราชสีมา'], dtype=object)

In [ ]:
data_covid['province_of_onset'].value_counts() #นับจำนวนข้อมูลแต่ละจังหวัด

province_of_onset
กรุงเทพมหานคร     57632
ชลบุรี            12941
ขอนแก่น           12821
สมุทรปราการ       11826
นนทบุรี           10641
                  ...
ส​งขลา                1
นครศรีธรรมราช​        1
ชอนแก่น               1
สุทรสาคร              1
จันทรบุรี             1
Name: count, Length: 97, dtype: int64

#### .iloc ย่อมาจาก Integer Location
ใช้เลือกข้อมูลตามตำแหน่ง [แถว,คอลัมน์] การนับจะเริ่มจาก 0 1 2 ...
#ข้อดีของ iloc
* เหมาะเมื่อรู้ตำแหน่งของข้อมูล
* แต่ไม่ทราบชื่อคอลัมน์
ใช้งานสะดวกในการเลือกช่วงข้อมูล

In [ ]:
data_covid.iloc[4,7] #ใช้เพื่อวนลูปได้ง่าย

'เชียงใหม่'

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [ ]:
smaller_table = data_covid[['announce_date','province_of_onset','risk']] #เรียกคอลัมน์ที่ต้องการมาเรียงต่อกันคล้ายๆ ลิสต์ อย่าลืมใส่ '' ครอบชื่อคอลัมน์
smaller_table

       announce_date province_of_onset                  risk
0          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
1          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
2          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
3          12/4/2022               NaN  อยู่ระหว่างการสอบสวน
4          12/4/2022         เชียงใหม่  อยู่ระหว่างการสอบสวน
...              ...               ...                   ...
356607      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356608      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356609      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356610      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ
356611      1/5/2022               NaN      ทัณฑสถาน/เรือนจำ

[356612 rows x 3 columns]

#### ตัดเฉพาะ rows ที่ต้องการ

##### แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)

In [ ]:
data_covid.iloc[1:5,:]

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)

In [ ]:
data_covid[data_covid['province_of_onset']=='ขอนแก่น']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
3345,3909218,12/4/2022,11/4/2022,หญิง,27.0,ปี,Thailand,พระนครศรีอยุธยา,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,บ้านไผ่
3763,3909636,12/4/2022,11/4/2022,หญิง,47.0,ปี,Thailand,ปทุมธานี,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,ขอนแก่น,บ้านไผ่
3823,3909696,12/4/2022,11/4/2022,ชาย,53.0,ปี,Thailand,สระบุรี,ระบุไม่ได้,ขอนแก่น,น้ำพอง
8436,3914309,12/4/2022,11/4/2022,หญิง,35.0,ปี,Thailand,ระยอง,อยู่ระหว่างการสอบสวน,ขอนแก่น,มัญจาคีรี
10537,3916410,12/4/2022,11/4/2022,หญิง,32.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,อุบลรัตน์
...,...,...,...,...,...,...,...,...,...,...,...
350028,4255901,1/5/2022,30/4/2022,หญิง,24.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เวียงเก่า
350029,4255902,1/5/2022,30/4/2022,หญิง,38.0,ปี,Thailand,ขอนแก่น,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,ขอนแก่น,เมืองขอนแก่น
350030,4255903,1/5/2022,30/4/2022,หญิง,27.0,ปี,Thailand,ขอนแก่น,อื่นๆ,ขอนแก่น,เมืองขอนแก่น
353787,4259660,1/5/2022,30/4/2022,NaN,26.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,ขอนแก่น,อุบลรัตน์
353880,4259753,1/5/2022,30/4/2022,NaN,30.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,ขอนแก่น,พล

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [ ]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
5,3905878,12/4/2022,11/4/2022,หญิง,12.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่แตง
6,3905879,12/4/2022,11/4/2022,ชาย,32.0,ปี,Thailand,เชียงใหม่,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เชียงใหม่,แม่ริม
7,3905880,12/4/2022,11/4/2022,หญิง,55.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,สารภี

In [ ]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
5,3905878,12/4/2022,11/4/2022,หญิง,12.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่แตง

In [ ]:
eight_rows_covid['province_of_onset'] == 'เชียงใหม่'  #สร้าง list ของ logical expression

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7     True
Name: province_of_onset, dtype: bool

In [ ]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'เชียงใหม่']  #เราเอา 2 บรรทัดบนมาบวกกัน

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
5,3905878,12/4/2022,11/4/2022,หญิง,12.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่แตง
6,3905879,12/4/2022,11/4/2022,ชาย,32.0,ปี,Thailand,เชียงใหม่,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,เชียงใหม่,แม่ริม
7,3905880,12/4/2022,11/4/2022,หญิง,55.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,สารภี

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

### HW6

In [ ]:
data = data_covid[['sex','age','province_of_onset']]

In [ ]:
data

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0               NaN
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356607   ชาย   NaN               NaN
356608   ชาย   NaN               NaN
356609  หญิง   NaN               NaN
356610  หญิง   NaN               NaN
356611   ชาย   NaN               NaN

[356612 rows x 3 columns]

In [ ]:
data = data_covid.fillna(value={'sex':'ไม่รู้', 'province_of_onset':'ไม่รู้'})
data

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,ไม่รู้,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,ไม่รู้,NaN

In [ ]:
data_clean= data.dropna(subset=['age']) #data มี missing ต้องทำการclean data

In [ ]:
data_clean

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,ไม่รู้,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม
...,...,...,...,...,...,...,...,...,...,...,...
356591,4262464,1/5/2022,30/4/2022,ชาย,7.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ห้วยขวาง
356592,4262465,1/5/2022,30/4/2022,หญิง,27.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,หลักสี่
356593,4262466,1/5/2022,30/4/2022,ชาย,69.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,มีนบุรี
356594,4262467,1/5/2022,30/4/2022,ชาย,19.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,NaN
356595,4262468,1/5/2022,30/4/2022,หญิง,35.0,ปี,Thailand,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,NaN

In [ ]:
this_data_clean= data_clean[['sex','age','province_of_onset']]

In [ ]:
this_data_clean

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0            ไม่รู้
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356591   ชาย   7.0     กรุงเทพมหานคร
356592  หญิง  27.0     กรุงเทพมหานคร
356593   ชาย  69.0     กรุงเทพมหานคร
356594   ชาย  19.0     กรุงเทพมหานคร
356595  หญิง  35.0     กรุงเทพมหานคร

[325395 rows x 3 columns]

In [ ]:
Female = this_data_clean[this_data_clean['sex']=='หญิง']
Female['age']

0         54.0
1         36.0
2         31.0
4         33.0
5         12.0
          ...
356586    44.0
356587    49.0
356589     1.0
356592    27.0
356595    35.0
Name: age, Length: 186838, dtype: object

In [ ]:
Female = this_data_clean[this_data_clean['sex']=='หญิง']
Female.describe()

           sex       age province_of_onset
count   186838  186838.0            186838
unique       1     238.0                90
top       หญิง      28.0     กรุงเทพมหานคร
freq    186838    2519.0             27842

In [ ]:
Female = this_data_clean[this_data_clean['sex']=='หญิง'] & (this_data_clean['province_of_onset']=='ขอนแก่น')

In [ ]:
Male = this_data_clean[this_data_clean['sex']=='ชาย']
Male['age']

3         37.0
6         32.0
9         42.0
11        41.0
13        37.0
          ...
356588     6.0
356590    36.0
356591     7.0
356593    69.0
356594    19.0
Name: age, Length: 125159, dtype: object

In [ ]:
print(Female['age'].dtype)

object

In [ ]:
print(Female['age'].head(20))

0     54.0
1     36.0
2     31.0
4     33.0
5     12.0
7     55.0
8     45.0
10    37.0
12    28.0
15    39.0
16    34.0
17    88.0
18     9.0
22    39.0
24    41.0
25    24.0
26    26.0
29    55.0
30    68.0
32    26.0
Name: age, dtype: object

In [ ]:
total_age_sum = 0
N = 0

for a in Female['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)            # แปลงเป็น int
        if a > 0:
            total_age_sum += a
            N += 1

print( f'อายุเฉลี่ยของผู้หญิง {total_age_sum/N}')
#-----------------------------------------------------------------------------------
total_age_Male = 0
N = 0

for a in Male['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)            # แปลงเป็น int
        if a > 0:
            total_age_Male += a
            N += 1

print( f'อายุเฉลี่ยของผู้ชาย {total_age_Male/N}')
#-----------------------------------------------------------------
Female_KK = Female[Female['province_of_onset']=='ขอนแก่น']

sum_female_kk = 0
N_female_kk = 0
for a in Female_KK['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)
        if a > 0:
            sum_female_kk += a # sum = sum + a
            N_female_kk += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum_female_kk/N_female_kk}')

male_KK =Male[Male['province_of_onset']=='ขอนแก่น']

sum_male_kk = 0
N_male_kk = 0
for a in male_KK['age']:
    if str(a).isdigit():      # ตรวจว่ามีแต่ตัวเลข
        a = int(a)
        if a > 0:
            sum_male_kk += a # sum = sum + a
            N_male_kk += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น {sum_male_kk/N_male_kk}')
#-------------------------------------------------------------------------------------------

non_thai_patients_count = data_covid[data_covid['risk'] == 'คนต่างชาติเดินทางมาจากต่างประเทศ'].shape[0]
print(f"คนต่างชาติเดินทางมาจากต่างประเทศ': {non_thai_patients_count}")

อายุเฉลี่ยของผู้หญิง 41.51104253203066
อายุเฉลี่ยของผู้ชาย 39.34756559167694
อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 39.65815760266371
อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น 37.1078811369509
คนต่างชาติเดินทางมาจากต่างประเทศ': 13

In [ ]:
data_covid[data_covid['risk'] == 'คนต่างชาติเดินทางมาจากต่างประเทศ']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
21993,3927866,13/4/2022,12/4/2022,หญิง,20.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
68104,3973977,15/4/2022,14/4/2022,หญิง,30,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,ท่าสองยาง
68120,3973993,15/4/2022,14/4/2022,ชาย,69,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
68122,3973995,15/4/2022,14/4/2022,หญิง,53,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
107436,4013309,17/4/2022,16/4/2022,หญิง,27,ปี,NaN,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
107439,4013312,17/4/2022,16/4/2022,ชาย,42,ปี,NaN,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
124927,4030800,18/4/2022,17/4/2022,ชาย,46,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,แม่สอด
142164,4048037,19/4/2022,18/4/2022,ชาย,2,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
223050,4128923,23/4/2022,22/4/2022,หญิง,28.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
243139,4149012,24/4/2022,23/4/2022,หญิง,19.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,แม่สอด
243163,4149036,24/4/2022,23/4/2022,ชาย,22.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,ท่าสองยาง
318755,4224628,29/4/2022,28/4/2022,หญิง,17.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง
318757,4224630,29/4/2022,28/4/2022,หญิง,26.0,ปี,Burmese,ตาก,คนต่างชาติเดินทางมาจากต่างประเทศ,ตาก,อุ้มผาง

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
3        ชาย  37.0               NaN
4       หญิง  33.0         เชียงใหม่
...      ...   ...               ...
356607   ชาย   NaN               NaN
356608   ชาย   NaN               NaN
356609  หญิง   NaN               NaN
356610  หญิง   NaN               NaN
356611   ชาย   NaN               NaN

[356612 rows x 3 columns]

In [ ]:
female = this_data[this_data['sex']=='หญิง']
female['age']

0         54.0
1         36.0
2         31.0
4         33.0
5         12.0
          ...
356592    27.0
356595    35.0
356597     NaN
356609     NaN
356610     NaN
Name: age, Length: 203340, dtype: object

In [ ]:
a

'2'

In [ ]:
sum = 0
N = 0
for a in female['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum/N}')

TypeError: '>' not supported between instances of 'str' and 'int'

In [ ]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in female_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum/N}')

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape #(12423, 3)แสดงขนาดของข้อมูล(แถว,คอลัมน์)

(356612, 3)

In [ ]:
print(data_covid.shape)
print(data_covid.dropna().shape) #dropna ใช้ลบทุกแถวที่มีค่า NaN อย่างน้อย 1 ค่า จะไม่แก้ไขดาต้าเฟรมเิมแต่จะสร้างดาต้าเฟรมใหม่ชั่วคราว
#ลบเสร็จตรวจสอบข้อมูลที่เหลืออยู่ด้วย .shape

(356612, 11)
(262536, 11)

In [ ]:
this_data.dropna().shape

(290263, 3)

In [ ]:
this_data.dropna()

         sex   age province_of_onset
0       หญิง  54.0         เชียงใหม่
1       หญิง  36.0         เชียงใหม่
2       หญิง  31.0         เชียงใหม่
4       หญิง  33.0         เชียงใหม่
5       หญิง  12.0         เชียงใหม่
...      ...   ...               ...
356591   ชาย   7.0     กรุงเทพมหานคร
356592  หญิง  27.0     กรุงเทพมหานคร
356593   ชาย  69.0     กรุงเทพมหานคร
356594   ชาย  19.0     กรุงเทพมหานคร
356595  หญิง  35.0     กรุงเทพมหานคร

[290263 rows x 3 columns]

In [ ]:
this_data.dropna()
print(this_data.shape)

(356612, 3)

In [ ]:
this_data.dropna(inplace=True) # ใช้ลบแถวที่มีค่า Missing Value ออกจาก DataFrame และแก้ไขข้อมูลเดิมทันที

/tmp/ipykernel_23092/1648573161.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True) # ใช้ลบแถวที่มีค่า Missing Value ออกจาก DataFrame และแก้ไขข้อมูลเดิมทันที

In [ ]:
this_data.dropna(inplace=True)
print(this_data.shape)

(290263, 3)

/tmp/ipykernel_23092/2129530393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(356612, 3)

In [ ]:
this_data.dropna().shape

(290263, 3)

In [ ]:
this_data.dropna(subset=['age']).shape #ลบเฉพาะแถวที่คอลัมน์`age` เป็นค่า Missing แล้วแสดงขนาดของข้อมูลที่เหลือ

(325395, 3)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data.head()

    sex   age province_of_onset
0  หญิง  54.0         เชียงใหม่
1  หญิง  36.0         เชียงใหม่
2  หญิง  31.0         เชียงใหม่
3   ชาย  37.0               NaN
4  หญิง  33.0         เชียงใหม่

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}') #จำนวนแถว(จำนวนข้อมูล)
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 356612
จำนวน record หลัง drop missing ใน province 321770

In [ ]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
#แทนค่าNaNใน sex=ไม่รู้ age=-1 province_of_onset=ไม่รู้
this_data_updated.head() #แสดงข้อมูลหลังแทนค่า

    sex   age province_of_onset
0  หญิง  54.0         เชียงใหม่
1  หญิง  36.0         เชียงใหม่
2  หญิง  31.0         เชียงใหม่
3   ชาย  37.0            ไม่รู้
4  หญิง  33.0         เชียงใหม่

In [ ]:
this_data_updated[this_data_updated['sex']=='ไม่รู้'] #แสดงข้อมูลที่sex=ไม่รู้

           sex   age province_of_onset
704     ไม่รู้    -1             ลำปาง
705     ไม่รู้    -1             ลำปาง
706     ไม่รู้    -1             ลำปาง
707     ไม่รู้    -1             ลำปาง
708     ไม่รู้    -1             ลำปาง
...        ...   ...               ...
353978  ไม่รู้  35.0     กรุงเทพมหานคร
353979  ไม่รู้    -1         กาฬสินธุ์
353980  ไม่รู้  25.0     กรุงเทพมหานคร
353981  ไม่รู้  25.0     กรุงเทพมหานคร
353982  ไม่รู้  36.0     กรุงเทพมหานคร

[17655 rows x 3 columns]

In [ ]:
this_data_updated['province_of_onset']=='ไม่รู้' #ตรวจสอบว่าใน province_of_onset มีค่าเป็น`ไม่รู้`
# `True` แถวนั้นมีค่าเป็นไม่รู้
# `False` แถวนั้นมีค่าไม่ใช่ไม่รู้

0         False
1         False
2         False
3          True
4         False
          ...
356607     True
356608     True
356609     True
356610     True
356611     True
Name: province_of_onset, Length: 356612, dtype: bool

In [ ]:
data_covid[this_data_updated['province_of_onset']=='ไม่รู้'] #โค้ดนี้เป็นการใช้เงื่อนไขจาก this_data_update ไปกรอง data_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
12,3905885,12/4/2022,11/4/2022,หญิง,28.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
14,3905887,12/4/2022,11/4/2022,ชาย,24.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
22,3905895,12/4/2022,11/4/2022,หญิง,39.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
26,3905899,12/4/2022,11/4/2022,หญิง,26.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})
#แทนค่าMissing ใน province_of_onset เป็น`ไม่รู้`

In [ ]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

        sex   age province_of_onset
704     NaN   NaN             ลำปาง
705     NaN   NaN             ลำปาง
706     NaN   NaN             ลำปาง
707     NaN   NaN             ลำปาง
708     NaN   NaN             ลำปาง
...     ...   ...               ...
353978  NaN  35.0     กรุงเทพมหานคร
353979  NaN   NaN         กาฬสินธุ์
353980  NaN  25.0     กรุงเทพมหานคร
353981  NaN  25.0     กรุงเทพมหานคร
353982  NaN  36.0     กรุงเทพมหานคร

[17655 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)
เป็นฟังก์ชันของ Pandas DataFrame ที่ใช้วนลูปทีละแถวของตารางในแต่ละรอบจะได้
* index = เลขแถว
* row = ข้อมูลของแถวนั้น (Series)
ซึ่งแตกต่างจาก for a in df['age'] ที่วนเฉพาะคอลัมน์เดียว ใช้เมื่อสนใจข้อมูลคอลัมน์เดียว

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
for each_row in this_data.iterrows(): #each_row เป็น Tuple(index, row)
    # print(each_row)เลขแถว
    # print(each_row[1]) ข้อมูลของแถว
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
      #ดึงค่าในคอลัมน์ age แล้วเช็คว่า=20มั้ย และดึงค่าจากคอลัมน์ province_of_onsetแล้วเช็คว่าเป็นขอนแก่นมั้ย
        print(each_row)

(10647, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10647, dtype: object)
(10720, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10720, dtype: object)
(10883, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10883, dtype: object)
(10916, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10916, dtype: object)
(32982, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 32982, dtype: object)
(33045, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33045, dtype: object)
(33206, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33206, dtype: object)
(33207, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33207, dtype: object)
(33213, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33213, dtype: object)
(33474, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33474, dtype: object)
(33563, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33563, dtype: object)
(33587, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33587, dtype: object)
(33649, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33649, dtype: object)
(56006, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56006, dtype: object)
(56012, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56012, dtype: object)
(56237, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56237, dtype: object)
(56443, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56443, dtype: object)
(56617, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56617, dtype: object)
(56660, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56660, dtype: object)
(56792, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56792, dtype: object)
(56797, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56797, dtype: object)
(210018, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210018, dtype: object)
(210022, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210022, dtype: object)
(210035, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210035, dtype: object)
(210129, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210129, dtype: object)
(210213, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210213, dtype: object)
(210285, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210285, dtype: object)
(210347, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210347, dtype: object)
(210400, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210400, dtype: object)
(210401, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210401, dtype: object)
(210452, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210452, dtype: object)
(210620, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210620, dtype: object)
(210643, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210643, dtype: object)
(210762, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210762, dtype: object)
(210778, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210778, dtype: object)
(231564, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231564, dtype: object)
(231629, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231629, dtype: object)
(231671, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231671, dtype: object)
(231710, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231710, dtype: object)
(231803, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231803, dtype: object)
(231884, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231884, dtype: object)
(232124, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232124, dtype: object)
(232181, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232181, dtype: object)
(232216, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232216, dtype: object)
(232327, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232327, dtype: object)
(250319, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 250319, dtype: object)
(250417, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250417, dtype: object)
(250487, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250487, dtype: object)
(250631, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250631, dtype: object)
(250670, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250670, dtype: object)
(267051, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 267051, dtype: object)
(280806, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280806, dtype: object)
(280855, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280855, dtype: object)
(280857, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280857, dtype: object)
(280860, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280860, dtype: object)
(280978, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280978, dtype: object)
(281070, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281070, dtype: object)
(281074, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281074, dtype: object)
(281087, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 281087, dtype: object)
(295128, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295128, dtype: object)
(295212, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295212, dtype: object)
(295330, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 295330, dtype: object)
(295366, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295366, dtype: object)
(295371, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295371, dtype: object)
(309830, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 309830, dtype: object)
(310003, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310003, dtype: object)
(310016, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310016, dtype: object)
(310036, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310036, dtype: object)
(310140, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310140, dtype: object)
(323862, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 323862, dtype: object)
(323879, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323879, dtype: object)
(323984, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323984, dtype: object)
(324027, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 324027, dtype: object)
(337399, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337399, dtype: object)
(337517, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337517, dtype: object)
(337577, sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 337577, dtype: object)
(349843, sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 349843, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)
`.iloc` เป็นคำสั่งของ Pandas ที่ใช้เข้าถึงข้อมูล ตามตำแหน่งแถว (Row Index) และคอลัมน์ (Column Index) เหมือนการเข้าถึงอาร์เรย์ใน NumPy

In [ ]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

10647
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10647, dtype: object
10720
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10720, dtype: object
10883
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10883, dtype: object
10916
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 10916, dtype: object
32982
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 32982, dtype: object
33045
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33045, dtype: object
33206
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33206, dtype: object
33207
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33207, dtype: object
33213
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33213, dtype: object
33474
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33474, dtype: object
33563
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33563, dtype: object
33587
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 33587, dtype: object
33649
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 33649, dtype: object
56006
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56006, dtype: object
56012
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56012, dtype: object
56237
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56237, dtype: object
56443
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56443, dtype: object
56617
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56617, dtype: object
56660
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56660, dtype: object
56792
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 56792, dtype: object
56797
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 56797, dtype: object
210018
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210018, dtype: object
210022
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210022, dtype: object
210035
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210035, dtype: object
210129
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210129, dtype: object
210213
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210213, dtype: object
210285
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210285, dtype: object
210347
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210347, dtype: object
210400
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210400, dtype: object
210401
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210401, dtype: object
210452
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210452, dtype: object
210620
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 210620, dtype: object
210643
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210643, dtype: object
210762
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210762, dtype: object
210778
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 210778, dtype: object
231564
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231564, dtype: object
231629
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231629, dtype: object
231671
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231671, dtype: object
231710
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231710, dtype: object
231803
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231803, dtype: object
231884
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 231884, dtype: object
232124
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232124, dtype: object
232181
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 232181, dtype: object
232216
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232216, dtype: object
232327
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 232327, dtype: object
250319
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 250319, dtype: object
250417
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250417, dtype: object
250487
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250487, dtype: object
250631
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250631, dtype: object
250670
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 250670, dtype: object
267051
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 267051, dtype: object
280806
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280806, dtype: object
280855
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280855, dtype: object
280857
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280857, dtype: object
280860
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 280860, dtype: object
280978
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 280978, dtype: object
281070
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281070, dtype: object
281074
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 281074, dtype: object
281087
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 281087, dtype: object
295128
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295128, dtype: object
295212
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295212, dtype: object
295330
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 295330, dtype: object
295366
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295366, dtype: object
295371
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 295371, dtype: object
309830
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 309830, dtype: object
310003
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310003, dtype: object
310016
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310016, dtype: object
310036
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 310036, dtype: object
310140
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 310140, dtype: object
323862
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 323862, dtype: object
323879
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323879, dtype: object
323984
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 323984, dtype: object
324027
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 324027, dtype: object
337399
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337399, dtype: object
337517
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 337517, dtype: object
337577
sex                     หญิง
age                     20.0
province_of_onset    ขอนแก่น
Name: 337577, dtype: object
349843
sex                      ชาย
age                     20.0
province_of_onset    ขอนแก่น
Name: 349843, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset]
Index: []

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.
count  3.566120e+05
mean   4.084178e+06
std    1.029452e+05
min    3.905873e+06
25%    3.995026e+06
50%    4.084178e+06
75%    4.173331e+06
max    4.262484e+06

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

TypeError: unsupported operand type(s) for +: 'float' and 'str'

### ```.isnull()```

In [ ]:
data_covid.isnull()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
356607,False,False,False,False,True,True,True,False,False,True,True
356608,False,False,False,False,True,True,True,False,False,True,True
356609,False,False,False,False,True,True,True,False,False,True,True
356610,False,False,False,False,True,True,True,False,False,True,True
356611,False,False,False,False,True,True,True,False,False,True,True

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table